---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nexus
  name: nexus3-72
  labels:
    app: nexus3-72
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus3-72
  template:
    metadata:
      labels:
        app: nexus3-72
    spec:
      nodeSelector:
        kubernetes.io/hostname: assignment-worker2
      containers:
        - image: sonatype/nexus3:3.72.0
          name: nexus3
          ports:
            - containerPort: 8081
          volumeMounts:
            - mountPath: /nexus-data  
              name: nexus3-72
          securityContext:
            runAsUser: 0  
      volumes:
        - name: nexus3-72
          persistentVolumeClaim:
            claimName: nexus3-72-pvc
