apiVersion: v1
kind: Service
metadata:
  namespace: nexus
  name: nexus3-72-service
spec:
  type: ClusterIP
  ports:
    - name: nexus3-70-1
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: nexus3-72